from jinja2 import Template

DAILY = Template("""# Day {{day}} - Solana Bot Tournament

## Performance Summary
{% for bot, metric in metrics.items() %}
### {{bot}}
- **Balance**: {{balances.get(bot, 50.0)}} SOL
- **Win Rate**: {{metric.win_rate}}%
- **Average PnL**: {{metric.avg_pnl}} SOL
- **Max Drawdown**: {{metric.max_dd}} SOL

{% endfor %}

## Charts
![Balance Chart](day_{{day}}_chart.png)

---
*Generated on {{day}} by Solana Bot Tournament*
""")

WEEKLY = Template("""# Week {{wk}} Summary - Solana Bot Tournament

## Weekly Performance (Ending Day {{end_day}})
{% for bot, metric in metrics.items() %}
### {{bot}}
- **Week Win Rate**: {{metric.win_rate}}%
- **Week Average PnL**: {{metric.avg_pnl}} SOL
- **Week Max Drawdown**: {{metric.max_dd}} SOL

{% endfor %}

## Performance Trends
![Weekly Chart](week_ending_day_{{end_day}}_chart.png)

## Key Highlights
- Best performer: TBD
- Most consistent: TBD
- Biggest mover: TBD

---
*Week {{wk}} Summary | Generated by Solana Bot Tournament*
""")